name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Use 'docker compose' instead of 'docker-compose'
      - name: Build and start containers
        run: docker compose up -d --build

      - name: Check running containers
        run: docker compose ps

      - name: Verify Network and Volume
        run: |
          docker network ls | grep app-network
          docker volume ls | grep mongo-data

      - name: Stop containers
        run: docker compose down
